import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getAIProvider } from '@/lib/ai'
import type { Tables } from '@/lib/supabase/types'

export async function GET(request: Request) {
  const authHeader = request.headers.get('authorization')
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = createAdminClient()
  const results: { businessId: string; status: string; error?: string }[] = []

  try {
    const { data: autoBusinesses } = await admin
      .from('ai_permissions')
      .select('business_id, permissions, approval_mode, confidence_threshold')
      .eq('autopilot_enabled', true)

    if (!autoBusinesses || autoBusinesses.length === 0) {
      return NextResponse.json({ message: 'No businesses with autopilot enabled', results: [] })
    }

    const ai = getAIProvider()

    for (const entry of autoBusinesses) {
      const businessId = entry.business_id
      try {
        const permissions = (entry.permissions as Record<string, Record<string, boolean>> | null) ?? {}
        if (!permissions.marketing?.generate_adverts) {
          results.push({ businessId, status: 'skipped', error: 'generate_adverts disabled' })
          continue
        }

        const { data: business } = await admin
          .from('businesses')
          .select('*')
          .eq('id', businessId)
          .single() as { data: Tables<'businesses'> | null; error: unknown }

        if (!business) continue

        const { data: productsRaw } = await admin
          .from('products')
          .select('id, name, description, price, unit, currency, product_inventory(availability_status)')
          .eq('business_id', businessId)
          .eq('is_active', true)

        const { data: previousCampaigns } = await admin
          .from('campaigns')
          .select('title, content_type, caption, created_at')
          .eq('business_id', businessId)
          .order('created_at', { ascending: false })
          .limit(10)

        const mappedProducts = (productsRaw ?? []).map(p => {
          const inv = Array.isArray(p.product_inventory) ? p.product_inventory[0] : p.product_inventory
          return {
            id: p.id,
            name: p.name,
            description: p.description,
            price: p.price,
            unit: p.unit,
            currency: p.currency,
            availability_status: (inv as { availability_status?: string } | null)?.availability_status ?? 'available',
          }
        })

        const campaign = await ai.generateCampaign({
          businessName: business.name,
          businessDescription: business.description,
          brandVoice: business.brand_voice,
          targetAudience: business.target_audience,
          products: mappedProducts,
          previousCampaigns: previousCampaigns ?? [],
          contentType: 'product_promotion',
          platform: 'all',
        })

        const status = entry.approval_mode === 'auto' ? 'approved' : 'pending_approval'

        const { data: savedCampaign } = await admin.from('campaigns').insert({
          business_id: businessId,
          title: campaign.title,
          headline: campaign.headline,
          caption: campaign.caption,
          call_to_action: campaign.callToAction,
          hashtags: campaign.hashtags,
          image_prompt: campaign.imagePrompt,
          content_type: campaign.contentType,
          product_id: campaign.selectedProductId,
          platform: 'all',
          status,
          ai_generated: true,
        }).select('id').single()

        if (status === 'pending_approval') {
          await admin.from('notifications').insert({
            business_id: businessId,
            type: 'approval_needed',
            title: '⏳ Campaign needs your approval',
            message: `"${campaign.headline}" — generated by AI autopilot`,
            link: `/dashboard/campaigns`,
          })
        }

        await admin.from('ai_actions').insert({
          business_id: businessId,
          action_type: 'generate_campaign',
          description: `Daily autopilot: ${campaign.title}`,
          payload: { campaignId: savedCampaign?.id } as Record<string, unknown>,
          permission_required: 'marketing.generate_adverts',
          status: 'executed',
          completed_at: new Date().toISOString(),
        })

        results.push({ businessId, status: 'success' })
      } catch (err) {
        console.error(`[cron-daily] Error for ${businessId}:`, err)
        results.push({ businessId, status: 'error', error: err instanceof Error ? err.message : 'Unknown' })
      }
    }

    return NextResponse.json({ message: 'Daily campaign cron completed', results })
  } catch (err) {
    console.error('[cron-daily]', err)
    return NextResponse.json({ error: 'Cron failed' }, { status: 500 })
  }
}
